trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  BuildConfiguration: Release

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    useGlobalJson: false
    version: '8.x'

- script: dotnet restore TorahWayPodcast.sln
  displayName: 'Restore NuGet packages'

- script: dotnet build TorahWayPodcast.sln --configuration $(BuildConfiguration) --no-restore
  displayName: 'Build solution'

- script: dotnet test TorahWayPodcast.sln --configuration $(BuildConfiguration) --no-build --verbosity normal
  displayName: 'Run tests'
